version: "2"
services:

  node:
    image: tezos/tezos:latest
    hostname: node
    command: tezos-node
    ports:
      - 9732:9732
    expose:
      - '8732'
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: on-failure

  ## Duplicate the `baker/endorser/accuser` containers for each PROTOCOL
  ## in file `active_protocol_versions`
  baker:
    image: tezos/tezos:latest
    hostname: baker
    environment:
      - PROTOCOL=002-PtEmHRqt
    command: tezos-baker
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

  endorser:
    image: tezos/tezos:latest
    hostname: endorser
    environment:
      - PROTOCOL=002-PtEmHRqt
    command: tezos-endorser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

  accuser:
    image: tezos/tezos:latest
    hostname: accuser-PtEmHRqt
    environment:
      - PROTOCOL=002-PtEmHRqt
    command: tezos-accuser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

volumes:
  node_data:
  client_data:
